// This file was auto-generated by scripts/generate_widget_class.js
#include "plugin.hpp"

struct Viral_Modules_OSC : Module {
    enum ParamIds {
        FREQ_PARAM,
        FINE_PARAM,
        PWM_CV_PARAM,
        PULSE_WIDTH_PARAM,
        NUM_PARAMS
    };

    enum InputIds {
        PWM_CV_INPUT,
        SYNC_INPUT,
        VOCT_INPUT,
        NUM_INPUTS
    };

    enum OutputIds {
        SINE_OUTPUT,
        SQUARE_OUTPUT,
        TRI_OUTPUT,
        SAW_OUTPUT,
        NUM_OUTPUTS
    };

    Viral_Modules_OSC() {
        config(NUM_PARAMS, NUM_INPUTS, NUM_OUTPUTS, 0);
    }

    void process(const ProcessArgs &args) override {

    }
};


struct Viral_Modules_OSCWidget : ModuleWidget {
    Viral_Modules_OSCWidget(Viral_Modules_OSC *module) {
        setModule(module);
        setPanel(APP->window->loadSvg(asset::plugin(pluginInstance, "res/OSC.svg")));

        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));

        // Params
        addParam(createParamCentered<RoundLargeBlackKnob>(mm2px(Vec(25.403175001600204, 33.60189380013531)), module, Viral_Modules_OSC::FREQ_PARAM));
        addParam(createParamCentered<RoundBlackKnob>(mm2px(Vec(12.701587500800098, 53.74757829805338)), module, Viral_Modules_OSC::FINE_PARAM));
        addParam(createParamCentered<RoundBlackKnob>(mm2px(Vec(38.1047625024003, 69.34716635020644)), module, Viral_Modules_OSC::PWM_CV_PARAM));
        addParam(createParamCentered<RoundBlackKnob>(mm2px(Vec(38.1047625024003, 53.13821938976614)), module, Viral_Modules_OSC::PULSE_WIDTH_PARAM));

        // Inputs
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(42.505312502677505, 87.40092375550562)), module, Viral_Modules_OSC::PWM_CV_INPUT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(19.602450001234807, 87.40092375550562)), module, Viral_Modules_OSC::SYNC_INPUT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(8.151018750513455, 87.40092375550562)), module, Viral_Modules_OSC::VOCT_INPUT));

        // Outputs
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(8.151018750513453, 104.19305705430986)), module, Viral_Modules_OSC::SINE_OUTPUT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(19.602450001234804, 104.19305705430986)), module, Viral_Modules_OSC::SQUARE_OUTPUT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(31.05388125195615, 104.19305705430986)), module, Viral_Modules_OSC::TRI_OUTPUT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(42.505312502677505, 104.19305705430986)), module, Viral_Modules_OSC::SAW_OUTPUT));
    }
};


Model *modelViral_Modules_OSC = createModel<Viral_Modules_OSC, Viral_Modules_OSCWidget>("Viral-Modules-OSC");
